### ISSUE TITLE
Getting Error on default installation

### ISSUE THREAD

**Issue by ameygat** [x0rz/phishing_catcher#15]
I cloned the project installed , pip install -r requirements.txt
then while running python catch_phishing I am getting error:
`maximum recursion depth exceeded while calling a Python object`
```
~/phishing_catcher$ ./catch_phishing.py
certificate_update: 0cert [00:00, ?cert/s][ERROR:websocket] 2017-11-08 17:56:53,509 - error from callback <bound method CertStreamClient._on_error of <certstream.core.CertStreamClient object at 0x7fb9b7901bd0>>: maximum recursion depth exceeded while calling a Python object
[ERROR:websocket] 2017-11-08 17:56:59,220 - error from callback <bound method CertStreamClient._on_error of <certstream.core.CertStreamClient object at 0x7fb9b7901e10>>: maximum recursion depth exceeded while calling a Python object
^C[INFO:root] 2017-11-08 17:57:01,067 - Kill command received, exiting!!
```

**Comment by zlkfb** [comment]
Maybe you should set a recursion limit for now.

**Comment by barrelman70** [comment]
It is a certstream issue  https://github.com/CaliDog/certstream-python/issues/2

**Comment by Fitblip** [comment]
Yeah, this was my bad!

![](https://media3.giphy.com/media/l0HlTHgnDtIhkoZOg/giphy.gif)

I've pushed an updated client so things should be working again! Just run `pip install --upgrade certstream`, and sorry again for the breakage!
