### ISSUE TITLE
Error connecting to certstream

### ISSUE THREAD

**Issue by nabeelxy** [x0rz/phishing_catcher#22]
Could you explain why I get the following error when trying to run the script? 

[ERROR:root] 2017-12-03 09:15:13,384 - Error connecting to CertStream - [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:579) - Sleeping for a few seconds and trying again...

**Comment by Atavic** [comment]
I hope [this](https://www.ssllabs.com/ssltest/analyze.html?d=certstream.calidog.io&s=50.19.252.69&hideResults=on&latest) helps.

**Comment by edgarlg77** [comment]
nabeelxy you are probably using CentOS/RHEL 7. I had the same issue. Apparently python 2.7.5 on those OS's have a bug. [This should help](https://danieleriksson.net/2017/02/08/how-to-install-latest-python-on-centos/). Install a newer version of Python an use that instead of the default python that comes with the OS.

**Comment by nabeelxy** [comment]
I upgraded python to 2.7.14 (from 2.7.5) in CentOS. Now I get the following certificate error:

Error connecting to CertStream - [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:579)

**Comment by RealJigglypuff** [comment]
Did you find the solution?

**Comment by nabeelxy** [comment]
Nope, not yet; now I am getting the following error from certstream:

"Error connecting to CertStream - Handshake status 502"

**Comment by nabeelxy** [comment]
I filed the same issue under certstream project as well so that I can get some help from the folks who created it.

**Comment by nabeelxy** [comment]
I am getting the same error with python 3.6.

**Comment by jstocksix** [comment]
Guys, do a quick bit of research.

> Greetings! Certstream is currently down right now until I can figure out a billing dispute with Google and/or switch it back to Heroku (more info here). Sorry for the inconvenience!

[https://certstream.calidog.io/](https://certstream.calidog.io/)

**Comment by jstocksix** [comment]
Update: Should be back on line soon after moving back to Heroku. Follow creator for more here:

[https://twitter.com/fitblip](https://twitter.com/fitblip)

**Comment by nabeelxy** [comment]
Thank @jstocksix. It works again.

**Comment by x0rz** [comment]
Was a Certstream network issue

**Comment by HAE** [comment]
Is this project still alive?
Same issue above still persists

**Comment by beemparthiban** [comment]
I'm still facing the same issue.
ERROR:root] 2019-01-03 12:45:26,857 - Error connecting to CertStream - [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726) - Sleeping for a few seconds and trying again...

**Comment by kolmai** [comment]
I'm facing the same issue @x0rz - do you anticipate any updates?
`[ERROR:root] 2019-06-27 11:10:22,852 - Error connecting to CertStream - _ssl.c:335: No root certificates specified for verification of other-side certificates. - Sleeping for a few seconds and trying again...`

**Comment by CarlosLannister** [comment]
Any solutions to this?

**Comment by nixjobin** [comment]
if you are on centos7, you can install python3.6 via epel. Im getting the same error on the default python 2.7
`yum install epel-release`
`yum install python36`

**Comment by katesaikishore** [comment]
I am getting the same error on macOS BigSur 
`Python Version: 3.7`

**Comment by salixh5** [comment]
Same issue here. But it happens because of the SDK.
```
# uname -a
Linux roku 5.10.131-0-virt #1-Alpine SMP Tue, 19 Jul 2022 16:08:14 UTC x86_64 Linux
# python --version
Python 3.8.10
```
