### ISSUE TITLE
CertStreamClient error?

### ISSUE THREAD

**Issue by tmpzero** [x0rz/phishing_catcher#26]
Great project!
I've installed it via pip and are getting the following error;

$ ./catch_phishing.py
certificate_update: 0cert [00:00, ?cert/s][ERROR:websocket] 2018-08-14 17:03:04,419 - error from callback <bound method CertStreamClient._on_open of <certstream.core.CertStreamClient object at 0x7fa525fc73d0>>: _on_open() takes exactly 2 arguments (1 given)
[ERROR:websocket] 2018-08-14 17:03:06,919 - error from callback <bound method CertStreamClient._on_message of <certstream.core.CertStreamClient object at 0x7fa525fc73d0>>: _on_message() takes exactly 3 arguments (2 given)

Tried updating all required components to the latest but still the same error, 
tried python3 and python2.7.12, no difference
Guess its a certstremclient error..?

Anyone have any clues on what I should change?

**Comment by zlkfb** [comment]
Hi,

Did you try : pip install --upgrade certstream ?
Or maybe check : https://github.com/CaliDog/certstream-python/issues/2

Good luck & cheers.

**Comment by musashi242** [comment]
Have received the same exact issue with certstream today:
_____
[ERROR:websocket] 2018-08-15 18:07:22,108 - error from callback <bound method CertStreamClient._on_message of <certstream.core.CertStreamClient object at 0x7679f1b0>>: _on_message() takes exactly 3 arguments (2 given)
_____

I think it might be related to the version of python but similarly I've had no luck.  Anyone know how to address this?

**Comment by antHeater** [comment]
Same error here since yesterday.
Tried with python 2.7.12 + 3.5.2 + 3.6.5, upgrading certstream didn't help.

`[ERROR:websocket] 2018-08-21 10:38:24,325 - error from callback <bound method CertStreamClient._on_message of <certstream.core.CertStreamClient object at 0x7f237df1a1d0>>: _on_message() takes exactly 3 arguments (2 given)
`

**Comment by boxw3r** [comment]
I solved the problem installing the version 0.48.0 of the websocket-client.
It seems like the latest version is not working properly with this library.
Thanks CaliDog/certstream-python#18

**Comment by hackingportal** [comment]
It solved the problem by installing python web socket client 0.48.0:
https://sources.voidlinux.eu/python-websocket-client-0.48.0/

**Comment by antHeater** [comment]
You're right, thank you @boxw3r!
Here the [official 0.48.0 release of the websocket-client](https://github.com/websocket-client/websocket-client/releases/tag/v0.48.0).

**Comment by GossiTheDog** [comment]
Hey - same issue, using websocket-client 0.51 gives this error.

**Comment by swedishmike** [comment]
I got an issue open for this in the websocket-client project. It seems that more stuff than this is affected by this bug/feature. https://github.com/websocket-client/websocket-client/issues/467

**Comment by x0rz** [comment]
This should have been fixed with the fixed `requirements.txt`
