### ISSUE TITLE
ImportError: No module named 'certstream'

### ISSUE THREAD

**Issue by SamosHaven** [x0rz/phishing_catcher#4]
Hi, Trying to get this phishing catcher set up but keep running into this error. I have followed the set up and have installed certstream, entropy and tqdm.

Every time I try running './catch_phishing.py' it comes up with this error message:

Traceback (most recent call last):
  File "./catch_phishing.py", line 17, in <module>
    import certstream
ImportError: No module named 'certstream'

Know what the fix is?

**Comment by x0rz** [comment]
Did you install certstream with pip2 or pip3? Depending on that try python2 or python3

**Comment by SamosHaven** [comment]
perfect, used pip to install so tried pip3 and it worked. Cheers

**Comment by bulletbill88** [comment]
Traceback (most recent call last):
  File "./catch_phishing.py", line 14, in <module>
    import certstream
ImportError: No module named certstream

I am having this issue too now (9th March 2020)

**Comment by cibernicola** [comment]
Same here: 
```
pip3 install -r requirements.txt
Requirement already satisfied: termcolor==1.1.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (1.1.0)
Collecting certstream==1.10 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/49/23/8afbb8671b520f714894a418314862aedccafc28cddde2de41d710728cb2/certstream-1.10.tar.gz
Collecting entropy==0.10 (from -r requirements.txt (line 3))
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/entropy/

```
